FROM node:12.13
LABEL maintainer lucas.pelos@gmail.com

# Install the Angular CLI & NativeScript CLI
ENV REACT_SCRIPTS_VERSION  ~3.2.0

RUN npm install -g --unsafe-perm react-scripts@${REACT_SCRIPTS_VERSION}

# Configure app dir and volume
ENV APP_DIR /app

VOLUME ${APP_DIR}
WORKDIR ${APP_DIR}

# Add app dependencies to PATH
ENV PATH ${PATH}:${APP_DIR}/node_modules/.bin

# dev server port
EXPOSE 3000
