version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    command: >
      bash -c "
        yarn install &&
        yarn start"
